-- MySQL Script generated by MySQL Workbench
-- 03/13/15 16:50:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sysgda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sysgda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sysgda` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sysgda` ;

-- -----------------------------------------------------
-- Table `sysgda`.`tipoitens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`tipoitens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`itens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `valorcusto` DOUBLE NOT NULL,
  `valorcomercial` DOUBLE NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `idtipoitem` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nomeitem_UNIQUE` (`nome` ASC),
  INDEX `fk_itens_tipoitens1_idx` (`idtipoitem` ASC),
  CONSTRAINT `fk_itens_tipoitens1`
    FOREIGN KEY (`idtipoitem`)
    REFERENCES `sysgda`.`tipoitens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`telefones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ddd` INT NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `TYPE` VARCHAR(31) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(40) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `numeroconvidados` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `datacriacao` DATETIME NOT NULL,
  `dataevento` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`eventositens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`eventositens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idevento` INT NOT NULL,
  `iditem` INT NOT NULL,
  `quantidade` INT NOT NULL,
  INDEX `fk_eventos_has_itens_itens1_idx` (`iditem` ASC),
  INDEX `fk_eventos_has_itens_eventos1_idx` (`idevento` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_index` (`idevento` ASC, `iditem` ASC),
  CONSTRAINT `fk_eventos_has_itens_eventos1`
    FOREIGN KEY (`idevento`)
    REFERENCES `sysgda`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_has_itens_itens1`
    FOREIGN KEY (`iditem`)
    REFERENCES `sysgda`.`itens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomecompleto` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cpfcnpj` VARCHAR(14) NOT NULL,
  `nomeresponsavel` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `convidadosextras` INT NOT NULL,
  `nomeguerramilitar` VARCHAR(45) NULL,
  `endereco` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpfcnpjcliente_UNIQUE` (`cpfcnpj` ASC),
  UNIQUE INDEX `rgcliente_UNIQUE` (`rg` ASC),
  UNIQUE INDEX `nomecliente_UNIQUE` (`nomecompleto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`clienteseventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`clienteseventos` (
  `idevento` INT NOT NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idevento`, `idcliente`),
  INDEX `fk_eventos_has_clientes_clientes1_idx` (`idcliente` ASC),
  INDEX `fk_eventos_has_clientes_eventos1_idx` (`idevento` ASC),
  CONSTRAINT `fk_eventos_has_clientes_eventos1`
    FOREIGN KEY (`idevento`)
    REFERENCES `sysgda`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_has_clientes_clientes1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `sysgda`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`tiposervico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`tiposervico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`fornecedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `valorservico` DOUBLE NOT NULL,
  `email` VARCHAR(45) NULL,
  `endereco` VARCHAR(50) NOT NULL,
  `cpfcnpj` VARCHAR(14) NULL,
  `rg` VARCHAR(20) NULL,
  `site` VARCHAR(45) NULL,
  `idtiposervico` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fornecedores_tiposervico1_idx` (`idtiposervico` ASC),
  CONSTRAINT `fk_fornecedores_tiposervico1`
    FOREIGN KEY (`idtiposervico`)
    REFERENCES `sysgda`.`tiposervico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`fornecedoreseventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`fornecedoreseventos` (
  `idfornecedor` INT NOT NULL,
  `idevento` INT NOT NULL,
  PRIMARY KEY (`idfornecedor`, `idevento`),
  INDEX `fk_fornecedores_has_eventos_eventos1_idx` (`idevento` ASC),
  INDEX `fk_fornecedores_has_eventos_fornecedores1_idx` (`idfornecedor` ASC),
  CONSTRAINT `fk_fornecedores_has_eventos_fornecedores1`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `sysgda`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedores_has_eventos_eventos1`
    FOREIGN KEY (`idevento`)
    REFERENCES `sysgda`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`clientesitensextras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`clientesitensextras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `iditem` INT NOT NULL,
  `idevento` INT NOT NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itensextraseventos_itens1_idx` (`iditem` ASC),
  INDEX `fk_clientesitensextras_clienteseventos1_idx` (`idevento` ASC, `idcliente` ASC),
  UNIQUE INDEX `index_unique` (`iditem` ASC, `idevento` ASC, `idcliente` ASC),
  CONSTRAINT `fk_itensextraseventos_itens1`
    FOREIGN KEY (`iditem`)
    REFERENCES `sysgda`.`itens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientesitensextras_clienteseventos1`
    FOREIGN KEY (`idevento` , `idcliente`)
    REFERENCES `sysgda`.`clienteseventos` (`idevento` , `idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`lembretes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`lembretes` (
  `idlembrete` INT NOT NULL AUTO_INCREMENT,
  `texto` TEXT NOT NULL,
  `data` DATETIME NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlembrete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`telefonesfornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`telefonesfornecedores` (
  `idfornecedor` INT NOT NULL,
  `idtelefone` INT NOT NULL,
  INDEX `fk_telefonesfornecedor_fornecedores1_idx` (`idfornecedor` ASC),
  INDEX `fk_telefonesfornecedor_telefones1_idx` (`idtelefone` ASC),
  UNIQUE INDEX `idtelefone_UNIQUE` (`idtelefone` ASC),
  CONSTRAINT `fk_telefonesfornecedor_fornecedores1`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `sysgda`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefonesfornecedor_telefones1`
    FOREIGN KEY (`idtelefone`)
    REFERENCES `sysgda`.`telefones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`telefonesclientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`telefonesclientes` (
  `idcliente` INT NOT NULL,
  `idtelefone` INT NOT NULL,
  INDEX `fk_telefonescliente_clientes1_idx` (`idcliente` ASC),
  INDEX `fk_telefonescliente_telefones1_idx` (`idtelefone` ASC),
  UNIQUE INDEX `idtelefone_UNIQUE` (`idtelefone` ASC),
  CONSTRAINT `fk_telefonescliente_clientes1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `sysgda`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefonescliente_telefones1`
    FOREIGN KEY (`idtelefone`)
    REFERENCES `sysgda`.`telefones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`debito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`debito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idevento` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `valor` DOUBLE NULL,
  `operacao` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_debito_clienteseventos1_idx` (`idevento` ASC, `idcliente` ASC),
  CONSTRAINT `fk_debito_clienteseventos1`
    FOREIGN KEY (`idevento` , `idcliente`)
    REFERENCES `sysgda`.`clienteseventos` (`idevento` , `idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`parcela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`parcela` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iddebito` INT NOT NULL,
  `valor` DOUBLE NULL,
  `formapagamento` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `datapagamento` DATETIME NULL,
  `datavencimento` DATETIME NULL,
  `entrada` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parcela_debito1_idx` (`iddebito` ASC),
  CONSTRAINT `fk_parcela_debito1`
    FOREIGN KEY (`iddebito`)
    REFERENCES `sysgda`.`debito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysgda`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysgda`.`usuarios` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `nomecompleto` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
